name: github_users
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.5.0
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  http: ^0.12.2
  url_launcher: ^5.7.10
  number_slide_animation: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
